In [1]:
from datascience import *
import numpy as np

In [2]:
make_array(1, 2, 3, 4)

array([1, 2, 3, 4])

In [3]:
hourly_wages = make_array(18.75, 30.25, 25.24, 157.32)

In [4]:
hourly_wages

array([  18.75,   30.25,   25.24,  157.32])

In [5]:
np.sort(hourly_wages)

array([  18.75,   25.24,   30.25,  157.32])

In [6]:
new_wages = hourly_wages + 1

In [7]:
new_wages

array([  19.75,   31.25,   26.24,  158.32])

In [8]:
new_wages = hourly_wages * 1.5

In [9]:
new_wages

array([  28.125,   45.375,   37.86 ,  235.98 ])

In [10]:
hours_worked = make_array(10, 15, 10, 40)

In [11]:
earnings = new_wages * hours_worked

In [12]:
earnings

array([  281.25 ,   680.625,   378.6  ,  9439.2  ])

In [13]:
hours_worked = make_array(10, 10, 40)

In [14]:
earnings = new_wages * hours_worked

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [15]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [16]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [17]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [18]:
hours_worked = np.array([10, 15, 10, 40])

In [19]:
hours_worked

array([10, 15, 10, 40])

In [20]:
earnings = new_wages * hours_worked

In [21]:
earnings

array([  281.25 ,   680.625,   378.6  ,  9439.2  ])

In [22]:
np.sum(earnings)

10779.674999999999

In [23]:
np.average(new_wages)

86.834999999999994